"""add route to monitor sessions

Revision ID: 00c35528e3a9
Revises: ff1bde999fa3
Create Date: 2026-07-15 22:39:56.307307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c35528e3a9'
down_revision: Union[str, Sequence[str], None] = 'ff1bde999fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_sessions', sa.Column('route', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_sessions', 'route')
    # ### end Alembic commands ###
