"""add category to quiz sessions

Revision ID: 17b159fb551d
Revises: a7dc9d84a6fd
Create Date: 2026-07-21 20:59:00.919368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b159fb551d'
down_revision: Union[str, Sequence[str], None] = 'a7dc9d84a6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'category')
    # ### end Alembic commands ###
