"""add checklist sessions and session items

Revision ID: 2a9fab2531f7
Revises: 5c40d6336521
Create Date: 2026-07-14 20:11:16.241878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9fab2531f7'
down_revision: Union[str, Sequence[str], None] = '5c40d6336521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_session_items',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checklist_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'checklist_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_session_items')
    op.drop_table('checklist_sessions')
    # ### end Alembic commands ###
