"""add password reset tokens and session feedback

Revision ID: 2dfa38d266be
Revises: 7812fa33b880
Create Date: 2026-08-06 17:57:08.160566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfa38d266be'
down_revision: Union[str, Sequence[str], None] = '7812fa33b880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('session_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('learners', sa.Column('theme_preference', sa.String(length=10), nullable=True))
    # server_default necessario: SQLite nao aceita ADD COLUMN NOT NULL sem
    # default numa tabela que ja tem linhas (mesmo problema resolvido antes
    # na migration de learner_id, aqui sem FK entao nao precisa de batch mode).
    op.add_column(
        'learners',
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learners', 'notifications_enabled')
    op.drop_column('learners', 'theme_preference')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
