"""adiciona guided em practice_sessions

Revision ID: 4a793432210d
Revises: 45a833463075
Create Date: 2026-08-11 20:56:35.733843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a793432210d'
down_revision: Union[str, Sequence[str], None] = '45a833463075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default precisa ser sa.false() (não a string '0'): SQLAlchemy
    # traduz pro literal certo em cada dialeto — '0' funciona por acidente no
    # SQLite mas quebra no Postgres, que exige um boolean de verdade.
    op.add_column('practice_sessions', sa.Column('guided', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_sessions', 'guided')
    # ### end Alembic commands ###
